apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-app
spec:
  selector:
    matchLabels:
      app: nuxt-app
  replicas: 3
  template:
    metadata:
      labels:
        app: nuxt-app
    spec:
      containers:
        - name: nuxt-app
          image: your-node-nuxt-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: 'production'
            - name: DB_HOST
              value: 'mysql-service'
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: 'mydb'
            - name: DB_USER
              value: 'root'
            - name: DB_PASSWORD
              value: 'rootpassword'
---
apiVersion: v1
kind: Service
metadata:
  name: nuxt-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: nuxt-app
  type: NodePort
